[RoutingRule]
#三角洲
DOMAIN-KEYWORD,m.baidu.com,PROXY
DOMAIN-KEYWORD,www.4399.com,PROXY
DOMAIN-KEYWORD,h.4399.com,PROXY
PORT,10012,PROXY
PORT,65010,PROXY
DOMAIN-KEYWORD,baidu,DIRECT
DOMAIN-KEYWORD,ap6,DIRECT
DOMAIN-KEYWORD,qq,DIRECT
DOMAIN-KEYWORD,lua,DIRECT
DOMAIN-KEYWORD,llua,DIRECT
DOMAIN-KEYWORD,msdk,DIRECT
DOMAIN-KEYWORD,itop.qq.com,DIRECT
DOMAIN-KEYWORD,publicfaas.game.qq.com,DIRECT
DOMAIN-KEYWORD,qosidc,DIRECT
DOMAIN-KEYWORD,tpns.sh.tencent.com,DIRECT
DOMAIN,qos.gcloud.qq.com,DIRECT
DOMAIN-KEYWORD,cg.qq.com,DIRECT
DOMAIN-KEYWORD,weixin.qq.com,DIRECT
DOMAIN-KEYWORD,openmobile.qq.com,DIRECT
DOMAIN-KEYWORD,lanzou,DIRECT
DOMAIN-KEYWORD,.eydata.net,DIRECT
DOMAIN-KEYWORD,.myqcloud.com,DIRECT
DOMAIN-KEYWORD,.tcdnos.com,DIRECT
DOMAIN-KEYWORD,logo,DIRECT
DOMAIN-KEYWORD,img.picgo.net,DIRECT
DOMAIN-KEYWORD,cccimg.com,DIRECT
DOMAIN-KEYWORD,lknb666,DIRECT
DOMAIN-KEYWORD,nb08,DIRECT
DOMAIN-KEYWORD,qlogo,DIRECT
DOMAIN,down.qq.com,DIRECT
DOMAIN-KEYWORD,superbed,DIRECT
DOMAIN-KEYWORD,imgdb,DIRECT
DOMAIN-KEYWORD,gitee,DIRECT
DOMAIN-KEYWORD,image,DIRECT
DOMAIN-KEYWORD,t3,DIRECT
DOMAIN-KEYWORD,t3data,DIRECT
DOMAIN-KEYWORD,840fk,DIRECT
DOMAIN-KEYWORD,luoyew,DIRECT
DOMAIN-KEYWORD,open,DIRECT
DOMAIN-KEYWORD,xui,DIRECT
DOMAIN-KEYWORD,aegis,DIRECT
DOMAIN-KEYWORD,imgcache,DIRECT
DOMAIN-KEYWORD,qlogo,DIRECT
DOMAIN-KEYWORD,jiazhang,DIRECT
DOMAIN-KEYWORD,qq.com,DIRECT
DOMAIN,nj.cschannel.anticheatexpert.com,PROXY
DOMAIN,down.anticheatexpert.com,PROXY
DOMAIN-KEYWORD,ssl.msdk,DIRECT




IP-CIDR,120.0.0.0/8,DIRECT
IP-CIDR,39.0.0.0/8,DIRECT
IP-CIDR,120.221.0.0/16,DIRECT
IP-CIDR,120.222.0.0/16,DIRECT
IP-CIDR,140.0.0.0/16,DIRECT
IP-CIDR,150.139.0.0/16,DIRECT
IP-CIDR,182.254.116.117,DIRECT
IP-CIDR,43.154.240.179,DIRECT
IP-CIDR,43.154.240.99,DIRECT
IP-CIDR,61.151.229.52,DIRECT
IP-CIDR,101.89.42.96,DIRECT
IP-CIDR,117.131.23.224,DIRECT
IP-CIDR,183.194.238.78,DIRECT
IP-CIDR,116.128.169.246,DIRECT
IP-CIDR,116.128.169.179,DIRECT
PORT,10012,PROXY
PORT,443,REJECT
PORT,80,PROXY
FINAL,DIRECT
[RoutingDomainStrategy]
AsIs
[FreedomDomainStrategy]
AsIs
[LocalPolicy]
bufferSize = 4096
connIdle = 300
downlinkOnly = 0
handshake = 4
uplinkOnly = 0
[DnsServer]
114.114.114.114
[DnsRule]
[DnsHost]
[DnsClientIp]
[Log]
loglevel = none
[PerAppVpn]
[PerAppMode]
[PerAppAllow]
[PerAppDisallow]
